### ISSUE TITLE
Infer on single video 

### ISSUE THREAD

**Issue by nikky4D** [SydCaption/SAAT#1]
Hi,
Thank you for this work. It looks good. 
I would like to try it out on my own video. Can you tell me how I can use your code for single video captioning?

**Comment by SydCaption** [comment]
> Hi,
> Thank you for this work. It looks good.
> I would like to try it out on my own video. Can you tell me how I can use your code for single video captioning?

Sure. I'll update it soon~

**Comment by SydCaption** [comment]
Hi, I add related files in ./misc

**Comment by nikky4D** [comment]
Thank you so much. I appreciate it.
