### ISSUE TITLE
Could you upload  your MaskRCNN code  version which you have changed for extracting roi_box and roi_feats?

### ISSUE THREAD

**Issue by AcodeC** [SydCaption/SAAT#10]

**Comment by SydCaption** [comment]
Hi, a bit busy, I'll upload it soon.

**Comment by AcodeC** [comment]
> Hi, a bit busy, I'll upload it soon.

Thank you for your kindly reply

**Comment by SydCaption** [comment]
Hi, I've uploaded, please check the shared link~
@AcodeC

**Comment by AcodeC** [comment]
> Hi, I've uploaded, please check the shared link~
> @AcodeC

Ｉsee it, thank you very much!

**Comment by AcodeC** [comment]
> Hi, I've uploaded, please check the shared link~
> @AcodeC

It seems that the ./demo/predictor.py file is not packed in the zip file. Could you please update it? Thank your for your help!

**Comment by SydCaption** [comment]
Sorry for that, I've updated.

**Comment by AcodeC** [comment]
> Sorry for that, I've updated.

Thank you very much
