### ISSUE TITLE
About the feature extracting

### ISSUE THREAD

**Issue by RyanLiut** [SydCaption/SAAT#11]
Hi,
    Thanks for the code. I would like to ask if you finetune the model in the MSVD/MSVTT after using the pretrained C3D on Sports 1M dataset? (Or just forward the model in the video dataset)

Thanks.

**Comment by SydCaption** [comment]
Hi, I didn't finetune any feature-extraction model.

**Comment by RyanLiut** [comment]
Thanks for the reply!
