### ISSUE TITLE
About the dataset MSVD

### ISSUE THREAD

**Issue by RyanLiut** [SydCaption/SAAT#12]
Hi,
    Thanks for the code! I wonder where can I find the map from Vid_id (Like Vid23) in the file to the VideoID in the MSVD corpus (Like "-4wsuPCjDBc").
     Thank you!

**Comment by SydCaption** [comment]
Hi, I added it in the data link~
@RyanLiut

**Comment by RyanLiut** [comment]
@SydCaption Many thanks!
