### ISSUE TITLE
About preprocess

### ISSUE THREAD

**Issue by mikittt** [SydCaption/SAAT#13]
I want to know how to make lables_svo in msrvtt_train_sequencelabel.h5 so that I can preprocess the data on my own.
In your paper, this is produced by using nltk. Could you give me more details?

**Comment by SydCaption** [comment]
Hi, I used the code from this [repo](https://github.com/acrosson/nlp/tree/master/subject_extraction).

**Comment by mikittt** [comment]
I see. Thank you for your quick reply!
