### ISSUE TITLE
About the best checkpoint

### ISSUE THREAD

**Issue by AcodeC** [SydCaption/SAAT#14]
Hi, when i run this code, after each epoch, it generated the new checkpoint. But in some epoch, there is a best score. Do i need to early stop or just run 200 epoches to get it's final checkpoint. Do the final checkpoint is the best performance checkpoint?

**Comment by SydCaption** [comment]
The max epochs is set as 200, with max patience 50. The training stops when no better model found within 50 epochs. I didn't add extra early stop. Hope this can help~

**Comment by AcodeC** [comment]
> The max epochs is set as 200, with max patience 50. The training stops when no better model found within 50 epochs. I didn't add extra early stop. Hope this can help~

You mean the final checkpoint in ./output/model_svo/xe/  is the best model?

**Comment by SydCaption** [comment]
Yep, if no better one appears within the latest 50 epochs.

**Comment by AcodeC** [comment]
> Yep, if no better one appears within the latest 50 epochs.

Thank you very much!
