### ISSUE TITLE
About the evaluation of the verb accuracy

### ISSUE THREAD

**Issue by mikittt** [SydCaption/SAAT#16]
Thank you for the code.
Are you planning to upload the code for evaluating verb accuracy? I would like to know how to calculate the accuracy when the ground truth sentences for one video contain different verbs and there are multiple correct verbs.

**Comment by SydCaption** [comment]
Hi, I uploaded sample code in ./misc~

**Comment by mikittt** [comment]
Thank you for your kindness!
