### ISSUE TITLE
About the frame features

### ISSUE THREAD

**Issue by RyanLiut** [SydCaption/SAAT#18]
Hi,

   Thanks for the paper and the code. I am wondering that when you used IRV2 to extract 2D frame features and selected 28 uniformly-spaced frames each video how do you aggregate these 28 feature vectors into one vector per video? Concatenate and project? Seemingly it is not clear in the paper.

Thank you!

**Comment by Dorothylyly** [comment]
i have the same question, did you find the answer?

**Comment by SydCaption** [comment]
Hi, it's also by mean-pooling.

**Comment by Dorothylyly** [comment]
thanks!!  I get it

**Comment by fsh2017** [comment]
> thanks!! I get it

The shape of NPY is (28,1000), and the shape of H5 is (1536,1). How to conduct mean pooling?
