### ISSUE TITLE
ModuleNotFoundError: No module named 'pyciderevalcap'

### ISSUE THREAD

**Issue by ydwl-lynn** [SydCaption/SAAT#19]
When I run <make -f Makefile_msrvtt_svo train GID=0 EXP_NAME=xe FEATS="irv2 c3d category" BFEATS="roi_feat roi_box" USE_RL=0 CST=0 USE_MIXER=0 SCB_CAPTIONS=0 LOGLEVEL=DEBUG MAX_EPOCH=100 LAMBDA=20> to train the dataset, the following error occurred:
![Snipaste_2020-10-22_10-59-26](https://user-images.githubusercontent.com/56346294/96819209-aa7c9880-1455-11eb-983f-c728a0e487d8.png)
I have download CIDEr and migrate to python3。(https://github.com/plsang/cider/pull/1)
Do you know the reason for this？

**Comment by SydCaption** [comment]
Hi, did you put it in coco-caption folder like this?
```
coco-caption
|__ pyciderevalcap
|__ pycocoevalcap
```

**Comment by ydwl-lynn** [comment]
I have do it, it's useful. Thank you very much.
