### ISSUE TITLE
How many GPU memory did you use?

### ISSUE THREAD

**Issue by tuyunbin** [SydCaption/SAAT#25]
Hi, I used a Titan XP to train or test your code, but I meet the error of 'cuda out of memory', so how can I use multi-gpu to train your code or how can I switch the dataset to MSVD?

**Comment by qizhust** [comment]
what batch size did you set?

**Comment by SydCaption** [comment]
what's the batch size you set?

**Comment by tuyunbin** [comment]
I just use the command you provided.

**Comment by SydCaption** [comment]
It's strange. I trained the model using a 16g GPU.

**Comment by tuyunbin** [comment]
Oh, maybe the needed gpu memory is more than the Titan xp which only has 12G&nbsp;



---Original---

**Comment by SydCaption** [comment]
You can try to slightly reduce the batch size to 56 or 48, though I remember it wasn't that much.

**Comment by tuyunbin** [comment]
OK, thank you!



---Original---
