### ISSUE TITLE
How to train with SCST?

### ISSUE THREAD

**Issue by Andrew-Zhu** [SydCaption/SAAT#26]
Hi, you have mentioned in the paper that

_Using reinforcement learning (SCST [43]), our model achieves the best result in terms of CIDEr and ranks second on the rest metrics._

and you train the model with

_make -f Makefile_msrvtt_svo train GID=0 EXP_NAME=xe FEATS="irv2 c3d category" BFEATS="roi_feat roi_box" USE_RL=0 CST=0 USE_MIXER=0 SCB_CAPTIONS=0 LOGLEVEL=DEBUG MAX_EPOCH=100 LAMBDA=20_

Could you provide the training script for the RL training?
Thanks a lot !!

**Comment by SydCaption** [comment]
Hi, it should be
```
make -f Makefile_msrvtt_svo train GID=0 EXP_NAME=scst FEATS="irv2 c3d category" BFEATS="roi_feat roi_box"  USE_RL=1 USE_CST=0 SCB_CAPTIONS=0 USE_MIXER=1 MIXER_FROM=1 USE_EOS=1 LOGLEVEL=DEBUG MAX_EPOCHS=100 START_FROM=path/of/pretrained
```

**Comment by Andrew-Zhu** [comment]
Thanks for your quick reply !
