### ISSUE TITLE
ROI Feat extraction bug

### ISSUE THREAD

**Issue by ashryaagr** [SydCaption/SAAT#29]
[Here](https://github.com/SydCaption/SAAT/blob/master/misc/extract_feats_roi.py#L37) 3 values are expected to be unpacked. But only 1 value is returned by the function `coco_demo.run_on_opencv_image(img)` . Because of this, an error is thrown when I run the roi extraction code in extract_feats_roi.py .
Did you use a modified predictor.py file which would return 3 values instead ? 

The current predictor.py file I am using is one provided [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py) by facebookresearch.

Or, i guess a possibility is that the extract_feats_roi.py was outdated because [this line](https://github.com/SydCaption/SAAT/blob/master/misc/extract_feats_roi.py#L32) has an undefined variable (though the issue in this line hardly matters. we can comment it out)

**Comment by SydCaption** [comment]
Hi, yes, please comment it out and find the maskrcnn_code.zip in google drive.
