### ISSUE TITLE
Error in make file "make: Nothing to be done for 'train'."

### ISSUE THREAD

**Issue by AcodeC** [SydCaption/SAAT#3]
Your work is awesome. When I use the code to train, I meet an error: "make: Nothing to be done for 'train'." I think the make file maybe wrong somewhere.

**Comment by SydCaption** [comment]
> Your work is awesome. When I use the code to train, I meet an error: "make: Nothing to be done for 'train'." I think the make file maybe wrong somewhere.

Hi, this is because the checkpoint already exists. You can move it to another tmp location or you can just change the lambda paramater a bit to generate a new file.

**Comment by AcodeC** [comment]
> > Your work is awesome. When I use the code to train, I meet an error: "make: Nothing to be done for 'train'." I think the make file maybe wrong somewhere.
> 
> Hi, this is because the checkpoint already exists. You can move it to another tmp location or you can just change the lambda paramater a bit to generate a new file.

OK, it works well now. You are very kindly. Many Thanks!
