### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by MarcusNerva** [SydCaption/SAAT#33]
When I run `make -f Makefile_msrvtt_svo train GID=0 EXP_NAME=xe FEATS="irv2 c3d category" BFEATS="roi_feat roi_box" USE_RL=0 CST=0 USE_MIXER=0 SCB_CAPTIONS=0 LOGLEVEL=DEBUG MAX_EPOCH=100 LAMBDA=20`
 
I got make: Nothing to be done for 'train'.
 What happend ?

When I want to train on MSVD, I got:
 make: *** No rule to make target 'output/feature/msrvtt_train_resnet_mp1.h5', needed by 'output/model_svo/xe/resnetc3dcategory_msrvtt_concat_CIDEr_64_0.0001_20.pth'.  Stop.
Can you upload Makefile_msvd_svo ?

**Comment by SydCaption** [comment]
For the 'Nothing to be done', it is because the target checkpoint has been generated. You can remove or rename the checkpoint and it should start training. I've uploaded the makefile for MSVD(yt2t) dataset.

**Comment by MarcusNerva** [comment]
Thanks for your reply! Now a new bug showed when I run `make -f Makefile_yt2t_svo train GID=0 EXP_NAME=xe FEATS="irv2 c3d category" BFEATS="roi_feat roi_box" USE_RL=0 CST=0 USE_MIXER=0 SCB_CAPTIONS=0 LOGLEVEL=DEBUG MAX_EPOCH=30 LAMBDA=20`

python: can't open file 'create_sequencelabel.py': [Errno 2] No such file or directory
Makefile_yt2t_svo:114: recipe for target 'output/metadata/yt2t_test_sequencelabel.h5' failed
make: *** [output/metadata/yt2t_test_sequencelabel.h5] Error 2

**Comment by qizhust** [comment]
Sorry for my late reply, please check [https://github.com/mynlp/cst_captioning](url) for the script you need.

**Comment by SydCaption** [comment]
Sorry for my late reply, please check [https://github.com/mynlp/cst_captioning](url) for the file you need. Or you can just download all the data files I provided on Google Drive.
