### ISSUE TITLE
When i use gen_roi_msrvtt.py get some problems

### ISSUE THREAD

**Issue by silverbulle** [SydCaption/SAAT#34]
When I run to get the return information from predictor.resize().

"RuntimeError: requested resize to (320, 240) ((320, 240) elements in total), but the given tensor has a size of 1024 (1024 elements). autograd's resize can only change the shape of a given tensor, while preserving the number of elements. "

Could you please tell me the resolution of the frame you are using?

 Is this my personal problem? I don't seem to see anyone else having this problem.

**Comment by SydCaption** [comment]
Hi, did you modify the output of resnet? The output is expected to be a vector (e.g., 1024-dim) from a fc-layer. You can check the maskrcnn_code.zip in Google drive for reference.

**Comment by silverbulle** [comment]
yeah, I reset the code to before the modification, it seems that there is no such problem. I will try again.  Thanks.

> Hi, did you modify the output of resnet? The output is expected to be a vector (e.g., 1024-dim) from a fc-layer. You can check the maskrcnn_code.zip in Google drive for reference.
