### ISSUE TITLE
Is it right to use 3D-ResNets-Pytorch for 3D motion features extraction?

### ISSUE THREAD

**Issue by MarcusNerva** [SydCaption/SAAT#35]
Hello amigo! I have a question about feature extraction for 3D motion features.
In the paper _Syntax-Aware Action Targeting for Video Captioning_, the author declares that he used C3D for motion features extraction. However, I am a little bit confused about the difference between '3D-ResNets' and 'C3D'. Are these two the same thing? 
Looking forward to your reply!

**Comment by SydCaption** [comment]
Hi, basically, you can use whatever conv3D models to extract the motion features. I did experiments on 3D-ResNets, and I didn't try other 3D feature extractors.

**Comment by MarcusNerva** [comment]
> Hi, basically, you can use whatever conv3D models to extract the motion features. I did experiments on 3D-ResNets, and I didn't try other 3D feature extractors.

Thank you for your quick reply. But you misunderstand what I mean.  I was wondering whether '3D-ResNets' and 'C3D' are the same thing?

**Comment by SydCaption** [comment]
Hi, I think C3D means 3D-CNN, so 3D-ResNets is a type of C3D.

**Comment by MarcusNerva** [comment]
> Hi, I think C3D means 3D-CNN, so 3D-ResNets is a type of C3D.

How about I3D? It seems that I3D is also a type of 3D-CNN.

**Comment by SydCaption** [comment]
Exactly!

MarcusNerva ***@***.***>于2021年7月14日 周三下午6:51写道：
