### ISSUE TITLE
How did your team extract objects features(ROI feats)？

### ISSUE THREAD

**Issue by MarcusNerva** [SydCaption/SAAT#36]
Did you extract ROI feats on every frame of this video? Or just on the center frame of this video? 
![image](https://user-images.githubusercontent.com/37070207/126928800-f50dd893-113a-4157-9605-eb8a61ae4e6f.png)
On your figure, it seems that you choose the center frame of the video. But you didn't mention it in your experiment section.

**Comment by qizhust** [comment]
the center frame

**Comment by SydCaption** [comment]
the center frame
