### ISSUE TITLE
Some questions about your work

### ISSUE THREAD

**Issue by MarcusNerva** [SydCaption/SAAT#37]
Thank you for your amazing work! Nevertheless, I still have some questions about your motivation.

As you mentioned in your paper(the abstract section): _**actions generated by existing methods may depend heavily on the co-occurrence of objects**, e.g. ‘driving’ is predicted with high conﬁdence whenever both man and car are detected._

I was wondering how did you notice this phenomenon. Did you reach this conclusion by making statistics on MSRVTT or MSVD dataset?  If so, how did you make these statistics? Looking forward to your reply!

**Comment by SydCaption** [comment]
Hi, I observed this phenomenon frequently, and found it was summarized as shortcut. I think [this paper](https://arxiv.org/abs/2004.07780) can be helpful.
