### ISSUE TITLE
Many Thanks!

### ISSUE THREAD

**Issue by AcodeC** [SydCaption/SAAT#4]

**Comment by SydCaption** [comment]
> Hi. your work is awesome. Now I have reproduce the SAAT result. I have noticed that there is a guidance from three syntax components (Trip-G) ablation study in your paper. But I do not find anything about (Trip-G) guidance in this code. Could you tell me how to do this ablation study? Thank you very much!

Hi, you can change the guiding signal by simply adjusting the 'pos' (Line437 in model_svo.py) or the 'svo_it' (Line439) variable~

**Comment by AcodeC** [comment]
Thank you very much! You help me a lot!

**Comment by AcodeC** [comment]
> > Hi. your work is awesome. Now I have reproduce the SAAT result. I have noticed that there is a guidance from three syntax components (Trip-G) ablation study in your paper. But I do not find anything about (Trip-G) guidance in this code. Could you tell me how to do this ablation study? Thank you very much!
> 
> Hi, you can change the guiding signal by simply adjusting the 'pos' (Line437 in model_svo.py) or the 'svo_it' (Line439) variable~

Ok, But the variable change to what?    pos[:,3:1]?, I do not know what the slice means.

**Comment by SydCaption** [comment]
Hi, the 'pos[:, 1:2]' means only using the 'verb' as guidance. For TripG, you can change it to 'pos[:, :]' so that the 'subject, verb, object' are all included.

**Comment by AcodeC** [comment]
> Hi, the 'pos[:, 1:2]' means only using the 'verb' as guidance. For TripG, you can change it to 'pos[:, :]' so that the 'subject, verb, object' are all included.

Thank you very much
